---
- name: Stop Service
  systemd:
    name: "{{ service_name }}"
    state: stopped

- name: Configure Repositories
  import_role:
    name: common
  vars:
    install_java: false

- name: Copy Service from Archive Directory to System
  copy:
    src: "{{binary_base_path}}/lib/systemd/system/{{systemd_file|basename}}"
    remote_src: true
    dest: "{{systemd_file}}"
    mode: 0644
    force: true

- name: Update Override to Use New Version
  lineinfile:
    path: "{{ systemd_override }}"
    line: "ExecStart={{archive_config_base_path}}/confluent-{{confluent_package_version}}/bin/{{start_script}} {{config_file}}"
    regexp: "ExecStart={{archive_config_base_path}}/confluent-(.*)/bin/{{start_script}} {{config_file}}"

- name: Restart Service
  systemd:
    daemon_reload: true
    name: "{{ service_name }}"
    state: restarted
