---
- name: Get Kafka Cluster Id
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    copy_certs: false

- name: Register KSQL Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/registry/clusters"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      [
          {
              "clusterName": "{{ksql_cluster_name}}",
              "scope": {
                  "clusters": {
                      "kafka-cluster": "{{kafka_cluster_id}}",
                      "ksql-cluster": "{{ksql_final_properties['ksql.service.id']}}"
                  }
              },
              "hosts": [ {% for host in groups['ksql'] %}{% if loop.index > 1%},{% endif %}{ "host": "{{host}}", "port": {{ksql_listener_port}} }{% endfor %}
              ],
              "protocol": "{{ksql_http_protocol | upper}}"
          }
      ]
    status_code: 204
  run_once: true
  register: output
