---
- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - name: Get Stats on Connect Hub installed Lib Directory
      stat:
        path: /usr/share/java/jcustenborder-kafka-connect-spooldir/lib
      register: lib_dir_stats

    - name: Assert ownership on lib directory
      assert:
        that:
          - lib_dir_stats.stat.gr_name == "confluent"
          - lib_dir_stats.stat.pw_name == "cp-kafka-connect"
