---
- name: Copy CA Cert to Host
  copy:
    remote_src: "{{ssl_custom_certs_remote_src}}"
    src: "{{ssl_ca_cert_filepath}}"
    dest: "{{ca_cert_path}}"

- name: Copy Signed Cert to Host
  copy:
    remote_src: "{{ssl_custom_certs_remote_src}}"
    src: "{{ssl_signed_cert_filepath}}"
    dest: "/var/ssl/private/{{service_name}}.chain"

- name: Extract Final Cert from Signed Cert Chain
  shell: |
    tac /var/ssl/private/{{service_name}}.chain | awk '!flag; /-----BEGIN CERTIFICATE-----/{flag = 1};' | tac > {{cert_path}}

- name: Copy Key to Host
  copy:
    remote_src: "{{ssl_custom_certs_remote_src}}"
    src: "{{ssl_key_filepath}}"
    dest: "/var/ssl/private/generation/{{service_name}}.key"

- name: Load Private Key
  slurp:
    src: "/var/ssl/private/generation/{{service_name}}.key"
  register: slurped_private_key

- name: Copy Key to Final Location - Non Encrypted
  copy:
    remote_src: true
    src: "/var/ssl/private/generation/{{service_name}}.key"
    dest: "{{key_path}}"
  when: "'BEGIN ENCRYPTED PRIVATE KEY' not in slurped_private_key.content|b64decode"

- name: Create Non Encrypted Private Key
  shell: |
    openssl rsa -in /var/ssl/private/generation/{{service_name}}.key \
      -out {{key_path}} {% if ssl_key_password is defined %}-passin pass:{{ssl_key_password}} -passout pass:{{ssl_key_password}}{% endif %}
  when: "'BEGIN ENCRYPTED PRIVATE KEY' in slurped_private_key.content|b64decode"
  no_log: "{{mask_secrets|bool}}"

- name: Create Keystore and Truststore from Certs
  include_tasks: create_keystores_from_certs.yml
