---
#### Confluent CLI Variables ####

### Confluent CLI supported architectures
confluent_cli_goarch:
  x86: "386"
  i386: "386"
  i686: "386"
  x86_64: "amd64"

### Filename of Confluent CLI binary inside the archive
confluent_cli_binary: confluent
